from full import FullConnection
from identity import IdentityConnection
from shared import SharedFullConnection, MotherConnection, SharedConnection
from linear import LinearConnection
from fullnotself import FullNotSelfConnection